# Dependencies
markdown:         kramdown
highlighter:      rouge
include:          ['_pages', '_subpages']

# Permalinks
permalink:        pretty

# Setup
title:            Women and Men in Greek Literature and Society
tagline:          'CLAS 101'
course_number:    'CLAS 101'
section_number:   '01'
semester:         'Spring 2022'
url:              https://libatique.info/CLAS101-S22
baseurl:

author:
  name:           'Daniel Libatique'
  url:            https://libatique.info

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dlibatique/CLAS101-S22
